[package]
name = "qnc-pixel-convert"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
qnc-media-metadata.workspace = true
serde.workspace = true
yuv = "=0.8.17"
fast_image_resize = { version = "=6.1.0", default-features = false, features = ["std"] }

[dev-dependencies]
serde_json.workspace = true
qnc-player-input.workspace = true
qnc-work-settings.workspace = true
qnc-media-stream.workspace = true
qnc-media-decode.workspace = true
qnc-ffmpeg-decode.workspace = true
qnc-video-output.workspace = true
sha2 = "0.10"
wgpu = "=24.0.5"
winit = "=0.30.13"
pollster = "=0.4.0"
